@rooturl=http://localhost:9004/api/v1

### auth end point
@authEP={{rooturl}}/auth

### Category end point
@categoryEP={{rooturl}}/categories

### product end point url
@productEP= {{rooturl}}/products

###get customer
GET {{authEP}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWF0IjoxNzQ0NTk4NzE1LCJleHAiOjE3NDQ2ODUxMTV9.q320GCrL9uSbAq028iTc0CxmQsQgtYev3qBVsz0RKMc
 
### register new customer
POST {{authEP}}/register
Content-Type: application/json

{
  "fName": "john",
  "lName":"Doe",
  "email":"johon@gmail.com",
  "phone":"1234567",
  "password":"password"
}
### login
POST {{authEP}}/login
Content-Type:application/json

 {
    "email":"john@gmail.com",
    "password":"password"
 }
###
POST {{categoryEP}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWF0IjoxNzQ0NTk4NzE1LCJleHAiOjE3NDQ2ODUxMTV9.q320GCrL9uSbAq028iTc0CxmQsQgtYev3qBVsz0RKMc
Content-Type:application/json

{
    "name":"nike",
    "adminId":"67ebb5578dcc2cfd5f4a52e3"
   
 }

### create a product
POST {{productEP}}
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWF0IjoxNzQ0NTk4NzE1LCJleHAiOjE3NDQ2ODUxMTV9.q320GCrL9uSbAq028iTc0CxmQsQgtYev3qBVsz0RKMc
{
"name" : "nike airmax 2025",
"description" : "launched at 2025 july",
"price": 200,
"stock":10,
"category":"67fcb388360b953b79588f42",
"thumbnail" : "https://wallpapercave.com/wp/rdYAno5.jpg",
"averageRating" : 0,
"reviews":"review id"

}

 
 